# Generated by Django 6.0.5 on 2026-07-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0003_aerolinea_servicio_checkin_factura_asiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeronave',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='aeronaves/'),
        ),
        migrations.AddField(
            model_name='aeropuerto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='aeropuertos/'),
        ),
        migrations.AddField(
            model_name='pasajero',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
