# Generated by Django 6.0.5 on 2026-07-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0004_aeronave_foto_aeropuerto_foto_pasajero_foto_perfil'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'cancelada'), _negated=True), fields=('vuelo', 'asiento'), name='asiento_unico_por_vuelo_activo'),
        ),
    ]
